'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
    Partial Friend NotInheritable Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
        
        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("27015")>  _
        Public Property Port() As Integer
            Get
                Return CType(Me("Port"),Integer)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("My Server GUI HD server")>  _
        Public Property ServerName() As String
            Get
                Return CType(Me("ServerName"),String)
            End Get
            Set
                Me("ServerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Level() As Integer
            Get
                Return CType(Me("Level"),Integer)
            End Get
            Set
                Me("Level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Content/SeriousSamHD/Levels/")>  _
        Public Property strLevel() As String
            Get
                Return CType(Me("strLevel"),String)
            End Get
            Set
                Me("strLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
        Public Property MaxPlayers() As Integer
            Get
                Return CType(Me("MaxPlayers"),Integer)
            End Get
            Set
                Me("MaxPlayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property InterChat() As String
            Get
                Return CType(Me("InterChat"),String)
            End Get
            Set
                Me("InterChat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property InterChatTime() As Integer
            Get
                Return CType(Me("InterChatTime"),Integer)
            End Get
            Set
                Me("InterChatTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AdminPass() As String
            Get
                Return CType(Me("AdminPass"),String)
            End Get
            Set
                Me("AdminPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowPass() As Boolean
            Get
                Return CType(Me("ShowPass"),Boolean)
            End Get
            Set
                Me("ShowPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property InfiniteAmmo() As Boolean
            Get
                Return CType(Me("InfiniteAmmo"),Boolean)
            End Get
            Set
                Me("InfiniteAmmo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GameMode() As Integer
            Get
                Return CType(Me("GameMode"),Integer)
            End Get
            Set
                Me("GameMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientPass() As String
            Get
                Return CType(Me("ClientPass"),String)
            End Get
            Set
                Me("ClientPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AllowPause() As Boolean
            Get
                Return CType(Me("AllowPause"),Boolean)
            End Get
            Set
                Me("AllowPause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AllowHealth() As Boolean
            Get
                Return CType(Me("AllowHealth"),Boolean)
            End Get
            Set
                Me("AllowHealth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AllowArmor() As Boolean
            Get
                Return CType(Me("AllowArmor"),Boolean)
            End Get
            Set
                Me("AllowArmor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SpawnInvul() As Boolean
            Get
                Return CType(Me("SpawnInvul"),Boolean)
            End Get
            Set
                Me("SpawnInvul") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property WindowX() As Integer
            Get
                Return CType(Me("WindowX"),Integer)
            End Get
            Set
                Me("WindowX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property WindowY() As Integer
            Get
                Return CType(Me("WindowY"),Integer)
            End Get
            Set
                Me("WindowY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HealthStays() As Boolean
            Get
                Return CType(Me("HealthStays"),Boolean)
            End Get
            Set
                Me("HealthStays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ArmorStays() As Boolean
            Get
                Return CType(Me("ArmorStays"),Boolean)
            End Get
            Set
                Me("ArmorStays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AmmoStays() As Boolean
            Get
                Return CType(Me("AmmoStays"),Boolean)
            End Get
            Set
                Me("AmmoStays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WeaponsStay() As Boolean
            Get
                Return CType(Me("WeaponsStay"),Boolean)
            End Get
            Set
                Me("WeaponsStay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ExtraEnemies() As Boolean
            Get
                Return CType(Me("ExtraEnemies"),Boolean)
            End Get
            Set
                Me("ExtraEnemies") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FriendlyFire() As Boolean
            Get
                Return CType(Me("FriendlyFire"),Boolean)
            End Get
            Set
                Me("FriendlyFire") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RespawnInPlace() As Boolean
            Get
                Return CType(Me("RespawnInPlace"),Boolean)
            End Get
            Set
                Me("RespawnInPlace") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property Difficulty() As Integer
            Get
                Return CType(Me("Difficulty"),Integer)
            End Get
            Set
                Me("Difficulty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ExtraEnemyStrength() As Integer
            Get
                Return CType(Me("ExtraEnemyStrength"),Integer)
            End Get
            Set
                Me("ExtraEnemyStrength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ExtraEnemyStrengthPerPlayer() As Integer
            Get
                Return CType(Me("ExtraEnemyStrengthPerPlayer"),Integer)
            End Get
            Set
                Me("ExtraEnemyStrengthPerPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Cheats() As Boolean
            Get
                Return CType(Me("Cheats"),Boolean)
            End Get
            Set
                Me("Cheats") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property FragLimit() As Integer
            Get
                Return CType(Me("FragLimit"),Integer)
            End Get
            Set
                Me("FragLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TimeLimit() As Integer
            Get
                Return CType(Me("TimeLimit"),Integer)
            End Get
            Set
                Me("TimeLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property FPS() As Integer
            Get
                Return CType(Me("FPS"),Integer)
            End Get
            Set
                Me("FPS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11000")>  _
        Public Property MaxClientBPS() As Integer
            Get
                Return CType(Me("MaxClientBPS"),Integer)
            End Get
            Set
                Me("MaxClientBPS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property Minimal() As Integer
            Get
                Return CType(Me("Minimal"),Integer)
            End Get
            Set
                Me("Minimal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisableVoting() As Boolean
            Get
                Return CType(Me("DisableVoting"),Boolean)
            End Get
            Set
                Me("DisableVoting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomExec() As Boolean
            Get
                Return CType(Me("CustomExec"),Boolean)
            End Get
            Set
                Me("CustomExec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomExecString() As String
            Get
                Return CType(Me("CustomExecString"),String)
            End Get
            Set
                Me("CustomExecString") = value
            End Set
        End Property
    End Class
End Namespace
